version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    build:
      context: ./backend/.
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
  nginx:
    build: ./nginx/.
    ports:
      - "80:80"
    volumes:
      - static:/usr/share/nginx/html/