GET http://127.0.0.1:8000/api/v1/artists/

###

GET http://127.0.0.1:8000/api/v1/albums/

###

GET http://127.0.0.1:8000/api/v1/songs/

###

POST http://127.0.0.1:8000/api/v1/artists/
Content-Type: application/json

{
    "name": "qurixsity"
}

###

POST http://127.0.0.1:8000/api/v1/albums/
Content-Type: application/json

{
    "name": "РАЗНОС",
    "artist": 1001,
    "year": 2023
}

###

POST http://127.0.0.1:8000/api/v1/songs/
Content-Type: application/json

{
    "name": "toler",
    "album": 1003 
}

###

DELETE http://127.0.0.1:8000/api/v1/artists/1003/

###

DELETE http://127.0.0.1:8000/api/v1/songs/1002/
