name: Qortex workflow

on:
  push:
    branches:
      - dev

jobs:
  backend_linter_test:
    name: Test backend code with FLAKE8
    runs-on: ubuntu-latest
    steps:
    - name: Copy repository code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install lint requirements
      run: |
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements/requirements.lint.txt
    - name: Test with FLAKE8
      run: |
        python -m flake8 backend/.
  backend_project_pytest:
    name: Test backend code with PyTest
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.10
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD:  ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Copy repository code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install project requirements
      run: |
        python -m pip install --upgrade pip 
        pip install -r ./backend/requirements/requirements.test.txt
    - name: Test with PyTest
      env:
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: 5432
      run: |
        pytest